version: '3.4'

services:
  productservicejava:
    image: annafock/productservicejava
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: annafock/productservicedb
    build:
      context: .
      dockerfile: DockerfileDb
    ports:
      - "3307:3306"

